name: demo_casino
description: Demo casino app for AI UI automation testing

publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  http: ^1.1.0
  rive: ^0.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/cards/
    - assets/rive/
    - assets/fonts/
  
  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/DM Sans-Regular.ttf
        - asset: assets/fonts/DM Sans-Medium.ttf
          weight: 500
        - asset: assets/fonts/DM Sans-Bold.ttf
          weight: 700
        - asset: assets/fonts/DM Sans-Italic.ttf
          style: italic
        - asset: assets/fonts/DM Sans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/DM Sans-BoldItalic.ttf
          weight: 700
          style: italic
    
    - family: IBMPlexSansCondensed
      fonts:
        - asset: assets/fonts/IBM Plex Sans Condensed-Light.ttf
          weight: 300
        - asset: assets/fonts/IBM Plex Sans Condensed-Regular.ttf
        - asset: assets/fonts/IBM Plex Sans Condensed-Medium.ttf
          weight: 500
        - asset: assets/fonts/IBM Plex Sans Condensed-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/IBM Plex Sans Condensed-Bold.ttf
          weight: 700
    
    - family: Aldrich
      fonts:
        - asset: assets/fonts/Aldrich-Regular.ttf
